name: gds
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Hardware and Test
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog verilator
          pip install cocotb pytest
          cd test && make
